# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23f49e3078341cc43c3e9a680090180ffdb1afcb641c18b11b623e335c7a1d40fd49441e935b6c21cc74bb7dd17f7b7e784fb75d989af27c2f325ae1243efb61

test:
  secret_key_base: b2bdddeefdb6324182f4d9fb8cb14beeed5ae8d17a4326bc785e166a453c1838422c44fa2eb67e285a76bd961ae23f785433a985edd8d1c51743b87b607c83a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
